Refactor/net: split headers to proxy class
PrismLauncher/PrismLauncher pull request #1102
Opened 2023-06-02 03:31 UTC by Ryex

This PR splits the setting of headers out of the Net::Download class into a proxy class. This allows a more generic controll flow to use the download class without invoking a static cast on the QCoreApplication::inst() pointer 

(I'm trying to let things like the updater use the networks tasks)

2023-06-15 22:43 UTC, getchoo commented
is this complete? just wondering since i noticed the old `Net::Download` functions weren't removed yet, and i'm not sure if that's for backwards compatibility. otherwise lgtm :)

2023-06-25 19:47 UTC, Ryex commented
> is this complete? just wondering since i noticed the old `Net::Download` functions weren't removed yet, and i'm not sure if that's for backwards compatibility. otherwise lgtm :)

> is this complete? just wondering since i noticed the old `Net::Download` functions weren't removed yet, and i'm not sure if that's for backwards compatibility. otherwise lgtm :)

Ok this is fixed and finished.
Needed to add a compiler def to deal with the user agent and apply the changed to the `Upload` class too.

2023-06-25 23:19 UTC, Ryex commented
> is this complete? just wondering since i noticed the old `Net::Download` functions weren't removed yet, and i'm not sure if that's for backwards compatibility. otherwise lgtm :)

the old functions are still used in some places and outside the the main launcher int eh updater I'm building. which is the whole point of making this change.

2023-06-26 22:04 UTC, Trial97 commented
Maybe you can also unify Upload and Download as mostly the code base is the same.
Here is my idea: https://github.com/Ryex/PrismLauncher/compare/refactor/net-split-headers-to-proxy-class...Trial97:PrismLauncher:refactor/net-split-headers-to-proxy-class?expand=1

2023-06-27 04:34 UTC, Ryex commented
> Maybe you can also unify Upload and Download as mostly the code base is the same. Here is my idea: https://github.com/Ryex/PrismLauncher/compare/refactor/net-split-headers-to-proxy-class...Trial97:PrismLauncher:refactor/net-split-headers-to-proxy-class?expand=1

Id actually very much like that refactor. can you clean up that patch though? there seems to be a bunch of extraneous stuff in it.

2023-06-27 06:35 UTC, Trial97 commented
> Id actually very much like that refactor. can you clean up that patch though? there seems to be a bunch of extraneous stuff in it.

Done https://github.com/Ryex/PrismLauncher/pull/1

2023-06-27 19:09 UTC, Ryex commented
> > Id actually very much like that refactor. can you clean up that patch though? there seems to be a bunch of extraneous stuff in it.
> 
> Done [Ryex#1](https://github.com/Ryex/PrismLauncher/pull/1)

ty

2023-07-02 23:14 UTC, getchoo approved these changes
alright, previous issues look to be resolved; after running a few sets of downloads/updates from cf and modrinth, i haven't been able to find any regressions! the refactor also makes a lot of sense imo, along with the new netrequest class (and thanks trial for making that a separate pr, made it really easy to review for me :p)

adding this to the 8.0 milestone since a few others prs are dependent on it now

2023-08-01 18:16 UTC, TheKodeToad requested changes

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/ApiDownload.cpp
> + */
You should probably include MultiMC's license, as well as in other places (along with any applicable contributors)

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/ApiHeaderProxy.h
> +                   request.url().host() == QUrl(BuildConfig.MODRINTH_STAGING_URL).host()) {
(note) Should be moved in future

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/ApiHeaderProxy.h
> +    ApiHeaderProxy() : HeaderProxy(){};
```suggestion
    ApiHeaderProxy() : HeaderProxy() {}
```

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/HeaderProxy.h
> +    };
```suggestion
    }
```

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/NetRequest.h
> +    auto canAbort() const -> bool override { return true; };
```suggestion
    auto canAbort() const -> bool override { return true; }
```
\>:(

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/RawHeaderProxy.h
> +    RawHeaderProxy() : HeaderProxy(){};
```suggestion
    RawHeaderProxy() : HeaderProxy() {}
```

2023-08-01 18:16 UTC, TheKodeToad commented on launcher/net/Download.h
> +    explicit Download() : NetRequest() { logCat = taskDownloadLogC; };
```suggestion
    explicit Download() : NetRequest() { logCat = taskDownloadLogC; }
```

2023-08-02 01:52 UTC, Ryex commented on launcher/net/ApiDownload.cpp
> + */
Nah, the code in this fine is original. `NetRequest` now holds the reused code. which is why it has the referenced license.

2023-08-02 09:05 UTC, TheKodeToad commented on launcher/net/ApiDownload.cpp
> + */
The `make*` functions look very similar to in Download.cpp

2023-08-02 16:02 UTC, Ryex commented on launcher/net/ApiDownload.cpp
> + */
similar in name only. conforming to the same interface doesn't mean they aren't original.

2023-08-02 16:18 UTC, TheKodeToad commented on launcher/net/ApiDownload.cpp
> + */
huh? the function implementations look almost the same

2023-08-02 16:21 UTC, Ryex commented on launcher/net/ApiDownload.cpp
> + */
There are only so many ways to write them. They are new functions on a new class, the old functions still exist, there for these are original code. This is actually law in the US thanks to Oracle vs Google.

2023-08-04 14:06 UTC, TheKodeToad approved these changes

2023-08-04 18:02 UTC, Scrumplex approved these changes

2023-08-04 18:03 UTC, Ryex commented
ok, forgiven.

2023-08-04 18:31 UTC, Scrumplex commented
I don't trust my merge commits tbh. I used JetBrains' magic merge tool, and it might have done some questionable stuff. Let's just move it to staging instead

2023-08-04 18:31 UTC, merged