Support add to PATH on macOS
PrismLauncher/PrismLauncher pull request #112
Opened 2022-10-19 13:56 UTC by ryanccn

Incredibly early support. Permissions system is a wreck, a [future Qt API](https://codereview.qt-project.org/c/qt/qtbase/+/395084) is still under review, and Full Disk Access has been 
confirmed to not work.

I'll try and find how VS Code does it, since Electron is about as wack as Qt is :/

2022-10-27 08:52 UTC, mistic316 commented
can i know the reason for need of a path for prism?

2022-10-31 06:46 UTC, mistic316 commented
Could I know the use case for adding Prism path?
This PR does not make any reference to any issues.

2022-10-31 06:50 UTC, ryanccn commented
> Could I know the use case for adding Prism path? This PR does not make any reference to any issues.

@mistic316 Running Prism from the command line. Normally you'd do `/Applications/PrismLauncher.app/Contents/MacOS/prismlauncher` to execute it, this PR just ~~is supposed to~~ adds a convenient button to make a symlink in `/usr/local/bin` to enable you to directly access with `prismlauncher`.

2022-10-31 07:05 UTC, mistic316 commented
@ryanccn 
For this, a user needs to give administrative permission to Prism to add a path (since this is modifying a system directory), from my understanding.
For a simple minecraft launcher, this kind of privilege permission is unnecessary (think of it running as root).

Again, what would be the use case for running Prism from the command line?

2022-11-05 15:26 UTC, Scrumplex commented
Shouldn't this be handled by package managers?

2022-11-05 15:55 UTC, ryanccn commented
What no no on macOS there's no install process at all

2022-11-05 15:59 UTC, DioEgizio commented
> Shouldn't this be handled by package managers?

most people are just gonna just drag and drop to /Applications/ or ~/Applications/

but i do agree that this is quite hacky and unnecessary

2022-11-05 16:01 UTC, Scrumplex commented
I thought about brew/macports

2022-11-05 16:12 UTC, ryanccn commented
I don't know about ports, but usually you do not symlink casks, the ones that do install to PATH (such as 1Password's `op`) use .pkg package installers.

This is useful for when you want to be able to run `prismlauncher` anywhere and have it registered in the PATH, since if you wanted ease of access you would've made the symlink manually anyway. VS Code has this CLI feature because its CLI can be used to open files / folders in VS Code, and launching instances is a similar use case IMO

2022-11-08 01:01 UTC, ryanccn commented
review wen 💀

2022-11-08 01:05 UTC, AshtakaOOf commented
Never duh

2022-11-08 07:24 UTC, Scrumplex commented
Can't users just create the symlink manually?

2022-11-08 12:20 UTC, ryanccn commented
well it's simpler to have a button that does this in the launcher

2022-11-08 14:30 UTC, Scrumplex commented
Well, it makes sense for an IDE like VS Code to have that, as a user is going to start it frequently from the terminal. But for a Minecraft launcher, I don't really see a reason why you would need that. If you are the kind of person who would frequently run a launcher from the terminal, it would be better if you just did it yourself.

2022-11-08 15:32 UTC, ryanccn commented
Well, there's nothing to lose if you do add this feature and I've talked to some macOS users who would love to see this QoL feature even if it's a very simple one.

Other than that, this also simplifies launching instances from, for instance, Shortcuts or Raycast Script Commands, for even non technical users, because you only have to do `prismlauncher` instead of having to go into the .app and copy the whole path to the binary.

2022-11-14 06:02 UTC, mistic316 commented
@ryanccn 
> This one uses osascript to run a piece of AppleScript that asks for administrator privileges to run a command.

I still think this feature is not useful. Specially giving simple minecraft launcher admin privilege permission in order to use it.
Still, if you are going to add it, please make it something toggleable like in VS Code that is **not** enabled by default.

2022-11-14 09:38 UTC, ryanccn commented
> @ryanccn
> 
> > This one uses osascript to run a piece of AppleScript that asks for administrator privileges to run a command.
> 
> I still think this feature is not useful. Specially giving simple minecraft launcher admin privilege permission in order to use it. Still, if you are going to add it, please make it something toggleable like in VS Code that is **not** enabled by default.

It isn't enabled by default, have you even tested the feature I'm proposing here

2022-11-14 16:27 UTC, flowln approved these changes
i'm fine with this change

just please de-indent the pre-processor things (`#ifdef`and `#endif`)

2022-11-14 17:35 UTC, Scrumplex requested changes

2022-11-14 17:35 UTC, Scrumplex commented on launcher/ui/MainWindow.cpp
> +}
```suggestion
void MainWindow::on_actionAddToPATH_triggered() {
    auto binaryPath = APPLICATION->applicationFilePath();
    auto targetPath = QString("/usr/local/bin/%1").arg(BuildConfig.LAUNCHER_APP_BINARY_NAME);

    qDebug() << "Symlinking" << binaryPath << "to" << targetPath;
    
    QStringList args;
    args << "-e";
    args << QString("do shell script \"mkdir -p /usr/local/bin && ln -sf '%1' '%2'\" with administrator privileges").arg(binaryPath, targetPath);
    auto outcome = QProcess::execute("/usr/bin/osascript", args);

    if (!outcome) {
        QMessageBox::information(this, tr("Successfully added %1 to PATH").arg(BuildConfig.LAUNCHER_DISPLAYNAME), tr("%1 was successfully added to your PATH. You can now start it by running `%2`.").arg(BuildConfig.LAUNCHER_DISPLAYNAME, BuildConfig.LAUNCHER_APP_BINARY_NAME));
    } else {
        QMessageBox::critical(this, tr("Failed to add %1 to PATH").arg(BuildConfig.LAUNCHER_DISPLAYNAME), tr("An error occurred while trying to add %1 to PATH").arg(BuildConfig.LAUNCHER_DISPLAYNAME));
    }
}
```

2022-11-14 17:35 UTC, Scrumplex commented on launcher/ui/MainWindow.cpp
> +}
^ needs clang-format

2022-11-14 17:38 UTC, Scrumplex approved these changes

2022-11-14 17:39 UTC, Scrumplex commented
Someone needs to test this on macOS please (Don't have the means rn to verify)

2022-11-14 20:12 UTC, merged