Made cat scalable
PrismLauncher/PrismLauncher pull request #1127
Opened 2023-06-07 21:55 UTC by Trial97

Fixes #273

2023-06-14 16:54 UTC, getchoo approved these changes
worked for me, plus it's pretty cool :)

2023-06-28 15:00 UTC, TheKodeToad requested changes

2023-06-28 15:00 UTC, TheKodeToad commented on launcher/ui/instanceview/InstanceView.cpp
> +void InstanceView::setCatVisible(bool visible)
setPaintCat would be less confusing imo

2023-06-28 15:00 UTC, TheKodeToad commented on launcher/ui/instanceview/InstanceView.cpp
> +    m_catPixmap.load(QString(":/backgrounds/%1").arg(ThemeManager::getCatImage()));
I'm not sure if it'd work, but maybe if `visble` is `false` you could do `m_catPixmap = QPixmap()`

2023-07-03 11:08 UTC, TayouVR approved these changes
seems to work and code looks good to me

2023-07-03 11:18 UTC, TheKodeToad approved these changes

2023-07-03 13:46 UTC, merged