Mod List Export To Text
PrismLauncher/PrismLauncher pull request #1246
Opened 2023-06-22 13:09 UTC by Trial97

fixes #1152
This has just the mods to text

2023-06-25 07:56 UTC, DioEgizio commented
few issues:
- <img width="762" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/83089242/b92a2383-359b-4dcb-8d1c-569f1ec173e4"> this :P
- i think that it should be renamed from "text" to "Mod text" because all you're exporting is a mod list
- should probably support plaintext too
- it should have a save button where to save the html/md/plaintext

2023-06-26 08:36 UTC, DioEgizio reviewed
<img width="1222" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/83089242/3235b50b-0554-4f1a-af78-2fe303624f2f">
also the html renderer doesn't seem to correctly linebreak

2023-06-26 08:36 UTC, DioEgizio commented on launcher/ui/MainWindow.ui
> +    <string>ModList (txt)</string>
```suggestion
    <string>Mod List</string>
```

2023-06-26 08:36 UTC, DioEgizio commented on launcher/ui/dialogs/ExportToModListDialog.cpp
> +            exampleLine = "<ul><a href=\"{url}\">{name}</a>[{version}] by {authors}</ul>";
```suggestion
            exampleLine = "<ul><a href=\"{url}\">{name}</a> [{version}] by {authors}</ul>";
```

2023-06-26 08:36 UTC, DioEgizio commented on launcher/ui/dialogs/ExportToModListDialog.cpp
> +            exampleLine = "[{name}]({url})[{version}] by {authors}";
```suggestion
            exampleLine = "[{name}]({url}) [{version}] by {authors}";
```

2023-06-26 08:36 UTC, DioEgizio commented on launcher/ui/dialogs/ExportToModListDialog.cpp
> +            exampleLine = "name: {name}; url: {url}; version: {version}; authors: {authors};";
```suggestion
            exampleLine = "{name} ({url}) [{version}] by {authors}";
```

2023-06-26 08:55 UTC, Scrumplex commented
This is a weird feature. I don't really see the use case if people can just create mrpacks now anyway.

2023-06-26 08:57 UTC, DioEgizio commented
I can see the use of it tbh. You don't want an entire modpack for just listing your mods. It can be useful also for example to modpack creators that want to list their mod in their description. With this they can just export- mod list- markdown and they can just copy paste it. I can see many uses

2023-06-26 08:58 UTC, Trial97 commented
If not desired feel free to close this but also close the linked issue with an explanation of why this is not wanted

2023-06-26 09:00 UTC, DioEgizio commented
I think this is useful in many scenarios tbh

2023-06-26 09:02 UTC, Scrumplex commented
Well. This is something that can be automated using shell scripts. Like, I don't see how this feature fits in the context of a launcher.

2023-06-26 09:04 UTC, DioEgizio commented
Shell scripts parsing metadata information?

2023-06-26 09:10 UTC, Scrumplex commented
> Shell scripts parsing metadata information?

You can use tools like `yq` to read the Packwiz TOML files.

> It can be useful also for example to modpack creators that want to list their mod in their description

I haven't seen many modpacks do that (usually because the mod platform will already do it for you mostly)

---

I just don't think this feature belongs into the launcher. I really hate this word, but I think "bloat" fits well here. If we add niche features like this, we only increase the amount of maintenance needed in the future.

Also, where does this feature end? Are we gonna need an HTML and a BBCode export as well? Maybe someone needs to post the modlist in a Minecraft Forums post, which doesn't support Markdown

2023-06-26 09:14 UTC, Trial97 commented
> Also, where does this feature end? Are we gonna need an HTML and a BBCode export as well? Maybe someone needs to post the modlist in a Minecraft Forums post, which doesn't support Markdown

Well, this already supports HTML and for other stuff, I added a custom format that lets the user define how each line should look.

2023-06-26 09:14 UTC, DioEgizio commented
> You can use tools like yq to read the Packwiz TOML files.

It wouldn't need just to to that, but to read the metadata inside the mod file. At that point it's not even a shell scripts, it's a mod manager

> I haven't seen many modpacks do that (usually because the mod platform will already do it for you mostly)

Some do

2023-06-26 09:16 UTC, Scrumplex commented
Look. I usually try to look at the problem in an issue, instead of accepting their proposed solution to fix their problem. The issue states the following benefits:

> - Easy Sharing: Users can share the exported mod lists with others, making it simpler to discuss and compare mods.
> - Documentation: Exported mod lists can serve as documentation for reference or troubleshooting purposes.

Both of these can be achieved using the mrpack export. So why add another feature for the same purpose?

2023-06-26 09:19 UTC, DioEgizio commented
mrpack export can only be used for, well, modrinth mods and mods that can be redistributed. It doesn't work for CF only mods and feels redundant for just a mod list. Like imagine if someone asks you what mods you use with the links to them and you literally have to make an entire modpack. Not to mention you also might want to add the mods to an already existing instance

2023-06-26 09:22 UTC, Scrumplex commented
My problem with this is that this is intended to output to a human-readable format. You can't use an exported mod list to import it into another instance anyway. It would be a lot of manual work.

If you want to share your mods with a friend you could send them the list of the jar files, you could take a screenshot of your mods either in Prism or even in-game.

2023-06-26 09:24 UTC, DioEgizio commented
Still, I don't understand what's the problem with a human readable mod list. It's the reason why things like moddermore exist after all

2023-06-26 09:31 UTC, Scrumplex commented
The reasons against are 700 additional lines of code that have to be maintained.

2023-06-26 09:32 UTC, DioEgizio commented
I mean it's not like this is the only feature that could be considered niche. We literally have a java profiler option

2023-06-27 14:24 UTC, Trial97 commented
Now this would also implement the export options mentioned in the following issues https://github.com/PrismLauncher/PrismLauncher/issues/214, https://github.com/PrismLauncher/PrismLauncher/issues/1178 (no importing for this)
I'm linking them here so that they can be addressed once this PR is closed.

2023-07-11 11:30 UTC, DioEgizio approved these changes

2023-07-11 14:52 UTC, TheKodeToad commented
This is quite nice!

Maybe it should prompt to update/"sync" the mods?
I found a lot of URLs were missing...

2023-07-11 14:56 UTC, TheKodeToad commented
Ohh - also maybe `Optional Info` could change into buttons to insert the placeholders on the Custom option.

And instead of preventing the Template from being edited, you could detect when it's edited and switch to custom...

2023-07-11 19:52 UTC, Trial97 commented
Thanks for the feedback:
- instead of prompting to update mods, I added a message that should explain that the metadata is needed
- updated the template behavior 
- regarding Oprional info I can't really picture what you mean so I kept it as is

2023-07-11 20:07 UTC, TheKodeToad commented
Maybe have buttons to insert {author} etc...

2023-07-13 15:48 UTC, Trial97 commented
I don't know what to say about this...
If I go this route, I should remove the extra file types as they do not make sense anymore if the buttons change the template.
In that case, I would only have a custom and a template, is that what you want?

2023-07-13 16:45 UTC, TheKodeToad commented
Oops... no, I meant only have that behaviour in custom

2023-07-13 17:38 UTC, Trial97 commented
This should solve it then

2023-07-13 17:43 UTC, TheKodeToad commented
Nice :3

I'll try to properly review the changes now if i don't get distracted yet again :P

2023-07-14 20:04 UTC, TheKodeToad requested changes
I'm confused what the changes to dependencies are for...

2023-07-14 20:04 UTC, TheKodeToad commented on launcher/modplatform/helpers/ExportToModList.cpp
> +QString ExportToModList(QList<Mod*> mods, Formats format, OptionalData extraData)
```suggestion
QString exportToModList(QList<Mod*> mods, Formats format, OptionalData extraData)
```

2023-07-14 20:04 UTC, TheKodeToad commented on launcher/modplatform/helpers/ExportToModList.cpp
> +QString ExportToModList(QList<Mod*> mods, QString lineTemplate)
```suggestion
QString exportToModList(QList<Mod*> mods, QString lineTemplate)
```

2023-07-14 20:04 UTC, TheKodeToad commented on launcher/modplatform/helpers/ExportToModList.cpp
> +QString toMARKDOWN(QList<Mod*> mods, OptionalData extraData)
ARGHHHHHHHHHH!!!!!!!!!!

I think Markdown would make more sense :laughing:

2023-07-14 20:04 UTC, TheKodeToad commented on launcher/modplatform/helpers/ExportToModList.cpp
> +QString toPLAINTXT(QList<Mod*> mods, OptionalData extraData)
PlainTXT?

2023-07-14 20:17 UTC, Trial97 commented
> I'm confused what the changes to dependencies are for...

oops I think I merged the wrong develop(I will remove that)

2023-07-14 20:47 UTC, Trial97 commented
Ok now it should be merged ok

2023-07-15 12:26 UTC, TheKodeToad commented on launcher/ui/dialogs/ExportToModListDialog.ui
> +        <string>This depends on the mods meta data. To ensure the meta data run at least one time the mods update on the selected instance(no need to update the mods).</string>
```suggestion
        <string>This depends on the mods' metadata. To ensure it is available, run an update on the instance. Installing the updates isn't necessary.</string>
```

2023-07-15 16:14 UTC, TheKodeToad approved these changes
good! ty

2023-07-16 10:24 UTC, Scrumplex approved these changes

2023-07-16 10:24 UTC, Scrumplex commented
I still think this is an overkill feature, but eh

2023-07-16 10:24 UTC, merged

2023-07-24 08:21 UTC, DUCKONAROLL commented
Hi, I stumbled across this pull request because my enhancement was mentioned, so would it be possible to import the file this generates and automatically download the mods from their respective repositories like the download mods menu? It would add a lot of use to this feature.

2023-07-24 08:23 UTC, Scrumplex commented
> Hi, I stumbled across this pull request because my enhancement was mentioned, so would it be possible to import the file this generates and automatically download the mods from their respective repositories like the download mods menu? It would add a lot of use to this feature.

You can already do this using the Modrinth export feature. Just export your instance as a Modrinth modpack and import it somewhere else.

2023-07-24 08:24 UTC, DioEgizio commented
Same with the cf export but I think he's talking about when mods have different types providers