feat: add toggle for quilt beacon
PrismLauncher/PrismLauncher pull request #1357
Opened 2023-07-13 01:22 UTC by getchoo

following the announcement of (extremely basic) [telemetry](https://quiltmc.org/en/blog/2023-06-26-mau-beacon) being added to quilt, and their team recommending toggles being added to launchers - similar to their [installer](https://github.com/QuiltMC/quilt-installer/pull/39) - this adds the toggle to prism!

i also created a new mod loader settings section, in case we have ever want to add other loader specific settings in the future. i am considering hiding this for now in non quilt instance settings pages, but since the jvm argument isn't applied anyways, i think it's probably fine /shrug

2023-07-13 01:33 UTC, getchoo commented
adding this to 7.2 since quilt 0.19.2 is already available and we should probably get this out soon :p

2023-07-13 04:35 UTC, Leo40Git commented
I feel like this toggle should have more of a description (or just a link to the blog post).
"Quilt's Beacon" is pretty meaningless.

2023-07-13 07:01 UTC, Scrumplex commented on launcher/minecraft/MinecraftInstance.cpp
> + *  Copyright (C) 2022 TheKodeToad <TheKodeToad@proton.me>\
```suggestion
 *  Copyright (C) 2022 TheKodeToad <TheKodeToad@proton.me>
```

2023-07-13 07:01 UTC, Scrumplex commented on launcher/ui/pages/global/MinecraftPage.ui
> +             <string>Disable Quilt's Beacon</string>
```suggestion
             <string>Disable Quilt Loader Beacon</string>
```

2023-07-13 07:01 UTC, Scrumplex commented on launcher/ui/pages/instance/InstanceSettingsPage.ui
> +             <string>Disable Quilt's Beacon</string>
```suggestion
             <string>Disable Quilt Loader Beacon</string>
```

2023-07-13 09:09 UTC, TheEpicBlock commented
> "Quilt's Beacon" is pretty meaningless.
The wording used in the installer is: "Don't count me as a monthly user". You might want to copy that into something like "Don't count me as a monthly user of quilt" or "Don't count me into monthly quilt user statistics"

2023-07-13 10:50 UTC, TheKodeToad commented
Maybe good to support https://github.com/QuiltMC/quilt-loader/wiki/System-Properties in future too?

2023-07-14 00:59 UTC, getchoo commented
> I feel like this toggle should have more of a description (or just a link to the blog post). "Quilt's Beacon" is pretty meaningless.

i've added a tooltip. i think it's explanatory enough for most users, as the telemetry itself is pretty basic

2023-07-14 03:07 UTC, Ryex approved these changes

2023-07-14 08:23 UTC, Scrumplex commented
QuiltMC/rfcs#84

Marking this as blocked for now. Let's see what happens upstream first.

2023-07-14 08:36 UTC, gdude2002 commented
That RFC cannot pass at the moment, as 2 out of 3 admins have stated they do not support it, and the other one has been checked out of everything for a while now.

2023-07-14 09:14 UTC, Scrumplex commented
I guess we can keep this in scope for 7.2 then

2023-07-15 15:02 UTC, Scrumplex requested changes

2023-07-15 15:02 UTC, Scrumplex commented on launcher/ui/pages/global/MinecraftPage.cpp
> +    ui->disableQuiltBeaconCheckBox->setToolTip(tr("Disable Quilt loader's beacon for counting monthly active users"));
set this in the .ui file instead?

2023-07-15 15:02 UTC, Scrumplex commented on launcher/ui/pages/instance/InstanceSettingsPage.cpp
> +    ui->disableQuiltBeaconCheckBox->setToolTip(tr("Disable Quilt loader's beacon for counting monthly active users"));
ditto

2023-07-15 18:25 UTC, getchoo commented on launcher/ui/pages/global/MinecraftPage.cpp
> +    ui->disableQuiltBeaconCheckBox->setToolTip(tr("Disable Quilt loader's beacon for counting monthly active users"));
done!

2023-07-15 19:18 UTC, jamierocks commented
I think this should also contain something similar to Apple's 'Ask App Not To Track' popup - ask the user when an instance containing Quilt is launched for the first time.

<img width="213" alt="Screenshot 2023-07-15 at 20 16 37" src="https://github.com/PrismLauncher/PrismLauncher/assets/5103549/c6b74248-fd12-472b-a049-750ce7f8d6a9">

2023-07-15 19:21 UTC, getchoo commented
there's no tracking

2023-07-16 22:52 UTC, TheKodeToad approved these changes
I really need to sleep

2023-07-17 04:42 UTC, Scrumplex approved these changes

2023-07-17 04:42 UTC, merged