Fix/windows console attach
PrismLauncher/PrismLauncher pull request #1464
Opened 2023-07-30 20:38 UTC by Ryex

This changes how the windows console is attached so that io redirection works properly. Before this changes redirection was completely broken in windows. This is a step towards better cli.
this also drops the usage of insecure `freopen` and clears that warning.

2023-08-02 12:32 UTC, getchoo requested changes
i'll test this soon, but in the meantime see the following comment and maybe take a look at [this](https://learn.microsoft.com/en-us/windows/win32/procthread/creating-a-child-process-with-redirected-input-and-output) page from ms' wiki. i think it could help make this solution a bit nicer, but if the current implementation works it works 🤷🏻

2023-08-02 12:32 UTC, getchoo commented on launcher/WindowsConsole.cpp
> +    }
much of this is duplicated code and could be put into a separate function to make things a little neater

2023-08-02 16:25 UTC, Ryex commented
> i'll test this soon, but in the meantime see the following comment and maybe take a look at [this](https://learn.microsoft.com/en-us/windows/win32/procthread/creating-a-child-process-with-redirected-input-and-output) page from ms' wiki. i think it could help make this solution a bit nicer, but if the current implementation works it works 🤷🏻

That wiki page is actually mostly irrelevant to attaching to the console of a parent process

2023-08-05 21:26 UTC, Scrumplex approved these changes
tested on Windows 10 with PowerShell :+1:

2023-08-06 19:37 UTC, getchoo approved these changes
works for me as well :)

2023-08-06 19:37 UTC, merged