Update Nix docs
PrismLauncher/PrismLauncher pull request #1467
Opened 2023-07-31 15:53 UTC by Scrumplex

2023-07-31 16:48 UTC, getchoo requested changes
only other thing i suggest is mentioning how builds are cached by garnix, and how to add it to `substituters` with
```nix
{
  nix.settings = {
    trusted-substituters = [
      "https://cache.garnix.io"
    ];

    trusted-public-keys = [
      "cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g="
    ];
  };
}
```


testing pr builds with `nix run` or in a shell with `github:PrismLauncher/PrismLauncher?ref=pull/<PR_ID>/HEAD` also might be a cool mention

2023-07-31 16:48 UTC, getchoo commented on nix/README.md
> +# Prism Launcher Nix packaging
```suggestion
# Prism Launcher Nix Packaging
```
title case :p

2023-07-31 16:48 UTC, getchoo commented on nix/README.md
> +      # Optional: Override the nixpkgs input of prismlauncher to use the same revision as the rest of your flake
this should probably mention that overriding nixpkgs can break reproducibility with our flake

2023-07-31 16:48 UTC, getchoo commented on nix/README.md
> +          nixpkgs.overlays = [prismlauncher.overlays.default];
ditto

2023-07-31 16:48 UTC, getchoo commented on nix/README.md
> +          environment.systemPackages = [prismlauncher.packages.${pkgs.system}.prismlauncher];
this is perfectly reproducible assuming that nixpkgs hasn't been overridden. might be worth a mention

2023-07-31 16:48 UTC, getchoo commented on nix/README.md
> +nix-env -iA prismlauncher
```suggestion
nix-env -iA prismlauncher.prismlauncher
```
i'm pretty sure this is required with `nix-env` when using the `-A` flag

2023-07-31 17:30 UTC, getchoo approved these changes
lgtm :)

2023-08-14 19:49 UTC, Trial97 approved these changes

2023-08-15 08:36 UTC, merged