feat:Removed update disabled warning
PrismLauncher/PrismLauncher pull request #1526
Opened 2023-08-15 17:56 UTC by Trial97

fixes #1019 and #603
This checks for updates for disabled mods, but for safety they are by default disabled in the mod download menu.
This is because once updated the mod is enabled.

2023-08-15 20:27 UTC, TheKodeToad requested changes

2023-08-15 20:27 UTC, TheKodeToad commented on launcher/minecraft/mod/ModFolderModel.cpp
> +        if (modfilename == filename) {
This could definitely be cleaner. Firstly, the `.disabled` check is redundant - secondly, there should be a function or field in `Resource` for this

2024-06-09 05:15 UTC, Ryex approved these changes
LGTM

2024-08-03 14:35 UTC, TheKodeToad approved these changes

2024-08-03 14:38 UTC, merged