Removed mojang account type
PrismLauncher/PrismLauncher pull request #1656
Opened 2023-09-25 14:45 UTC by Trial97

The Mojang login is no longer supported as of this month.

2023-09-27 02:50 UTC, ColonelGerdauf approved these changes

2023-09-27 09:41 UTC, getchoo approved these changes
lgtm! after getting rid of the last remaining mentions of mojang accounts being supported that i could find, the only suggestion i have is removing/disabling the account type column in the account list. it seems a bit pointless now with only msa being supported

2023-09-27 09:52 UTC, Trial97 commented
we also support offline account type there so I vote to keep it.

2023-09-27 18:14 UTC, ColonelGerdauf commented
offline account type is quite useful for versions 1.5.2 and earlier, when the original Mojang launcher was not locked behind a login. Not to mention, without Koad's skin fix, there was no use for the accounts anyways.

And even for later versions, though I am not sure how well some of the components would work.

2023-09-30 16:55 UTC, getchoo commented
> we also support offline account type there so I vote to keep it.

oops! i forgot about that for a second haha

2023-09-30 17:04 UTC, TheKodeToad requested changes
might as well, right?

2023-09-30 17:04 UTC, TheKodeToad commented on launcher/LaunchController.cpp
> +                                                     "account logged in."
```suggestion
                                                     "account which owns Minecraft logged in."
```

2023-09-30 17:08 UTC, TheKodeToad commented on launcher/minecraft/auth/AccountList.cpp
> +                    return tr("Type of the account (currently only MSA is supported.)");
```suggestion
                    return tr("Type of the account - Msa or Offline.");
```

2023-09-30 19:42 UTC, Scrumplex approved these changes

2023-09-30 19:43 UTC, Scrumplex commented on launcher/minecraft/auth/AccountList.cpp
> +                    return tr("Type of the account (currently only MSA is supported.)");
```suggestion
                    return tr("Type of the account (MSA or Offline)");
```

2023-10-01 11:45 UTC, TheKodeToad approved these changes

2023-10-01 12:32 UTC, merged