chore:fixed some codeql warnings
PrismLauncher/PrismLauncher pull request #1679
Opened 2023-10-04 10:54 UTC by Trial97

This fixes some of the codeql warnings that can be found through code.
This should not change any functionality whatsoever.
This should be treated as a low-priority PR.

2023-12-11 10:05 UTC, Scrumplex commented
This isn't really high priority as you said, so let's move this to 9.0

2024-06-28 03:14 UTC, Ryex approved these changes

2024-10-29 14:03 UTC, TheKodeToad requested changes

2024-10-29 14:03 UTC, TheKodeToad commented on launcher/minecraft/auth/AccountList.cpp
> +QString getAccountStatus(AccountState status)
```suggestion
static QString getAccountStatus(AccountState status)
```

2025-03-26 01:41 UTC, TheKodeToad approved these changes

2025-03-26 06:05 UTC, merged