simplify microsoft login
PrismLauncher/PrismLauncher pull request #1799
Opened 2023-11-07 08:55 UTC by Trial97

Stolen from TheKodeToad from here: https://discord.com/channels/1031648380885147709/1031823065937629267/1171229791513493544

Please don't hesitate to suggest any text changes.
I kept the old behavior in case the user browser was not open or something was unclear.

Also tested and it works.

2023-11-07 18:36 UTC, TayouVR approved these changes
text could be a bit nicer, maybe like my suggestion below, but its fine either way (I want this entire dialog to get an overhaul some day x3)

2023-11-07 18:36 UTC, TayouVR commented on launcher/ui/dialogs/MSALoginDialog.cpp
> +                .arg(linkString, code));
```suggestion
        ui->label->setText(
            tr("<p>Please login in the opened browser. If no browser was opened please open up %1 in "
               "a browser and put in the code <b>%2</b> to proceed with login.</p>")
                .arg(linkString, code));
```

2023-11-08 00:06 UTC, getchoo requested changes
otherwise lgtm :)

2023-11-08 00:06 UTC, getchoo commented on launcher/ui/dialogs/MSALoginDialog.cpp
> +        ui->label->setText(tr("<p>Please login in the opened browser. If no browser was opened please open up %1 in "
```suggestion
        ui->label->setText(tr("<p>Please login in the opened browser. If no browser was opened, please open up %1 in "
```

2023-11-08 07:19 UTC, getchoo approved these changes

2023-11-08 07:21 UTC, getchoo commented
~~it would be so cool if we had automerge~~

2023-11-08 07:51 UTC, Scrumplex approved these changes

2023-11-08 07:51 UTC, merged

2023-11-08 10:52 UTC, TheKodeToad commented
wouldn't it be better to have a button instead of opening the browser straight away

2023-11-08 11:01 UTC, Trial97 commented
Not really as I want to simplify the process. not keep it the same.
Also a little late to the party as it was merged :(.
Feel free to open a PR where you can improve that behavior.

2023-11-08 15:51 UTC, TheKodeToad commented
ig it's fine