Improvements to catpack
PrismLauncher/PrismLauncher pull request #1822
Opened 2023-11-09 19:46 UTC by Trial97

fixes #693
fixes #1820 
and hopefully fixes #1816 (needs testing)

So here are the additions to the catpacks:
- if the default path points to a directory then we will display one cat per day from that directory in a slideshow manner (the files are sorted alphabetically then the file index is chosen by the following formula `theDayOfTheYear % numFiles`)
- if that directory is named `random` (case insensitive) then a new cat is selected on each prism restart or cat button toggle 
- make sure we apply smooth transformation when scaling of the cat

2023-11-12 13:15 UTC, SympathyTea commented
super excited about this one, hopefully it works out

2024-01-21 00:05 UTC, TheKodeToad requested changes
Looks pretty good!! Just one thing I noticed.

2024-01-21 00:05 UTC, TheKodeToad commented on launcher/ui/themes/CatPack.cpp
> +    auto idx = now.dayOfYear() % files.length();
```suggestion
    auto idx = (now.dayOfYear() - 1) % files.length();
```
First day = 1, first file = 0, that doesn't make sense and the you will always see the cat of tommorow

2024-01-21 00:16 UTC, TheKodeToad commented
Isn't choosing based on alphabetical order a little weird? It probably suffers from the classic issue of sorting numbers like e.g. `1`, `10`, `11`, `12`, `2`, `3`, `4`, `5` and requiring more concrete names would be better imo

2024-01-21 06:55 UTC, Trial97 commented
Well yeah if people want more control over it they can add a 0 before the digit like:
`01`, `02`, `03`, ...,`10` 
If they have more that 100 cats then add more zeros

2024-03-20 23:12 UTC, TheKodeToad approved these changes

2024-03-27 17:45 UTC, getchoo approved these changes

2024-03-28 12:48 UTC, merged