Added mod reinstall dialog
PrismLauncher/PrismLauncher pull request #1892
Opened 2023-11-24 22:20 UTC by Trial97

fixes #1354

Added one more button to the mods page that will open a dialog with the selected mod allowing you to select a new version to install.
Also added a tag to the installed version combobox to determine what is the installed version.

2023-11-26 23:54 UTC, getchoo requested changes
i'd recommend the button's name be changed to "change version" similar to the in version tab of instance settings - since that's a bit more descriptive, while "reinstall mod" sounds more like a troubleshooting method in the case a mod was installed incorrectly. it would also probably be nicer to have it near "check for updates" because of their similar functions

2023-11-26 23:54 UTC, getchoo commented on launcher/ui/pages/modplatform/ModPage.cpp
> +            m_ui->versionSelectionBox->addItem(QString("%1%2%3").arg(version.version, release_type, flag), QVariant(i));
```suggestion
            m_ui->versionSelectionBox->addItem(QString("%1%2 %3").arg(version.version, release_type, flag), QVariant(i));
```
the space could also go in the original variable, but things like `[release][installed]` is kinda ugly to me

2023-11-27 07:42 UTC, Trial97 commented on launcher/ui/pages/modplatform/ModPage.cpp
> +            m_ui->versionSelectionBox->addItem(QString("%1%2%3").arg(version.version, release_type, flag), QVariant(i));
I understand that the current flags are ugly, but I have negative UX skills so if you make any kind of suggestions please be very specific. For now added the space before it and also moved and renamed the button.

2023-12-11 19:45 UTC, TayouVR approved these changes
works 👍

2024-06-09 06:32 UTC, Ryex approved these changes

2024-06-17 16:35 UTC, Trial97 commented
@getchoo other than java this is the last PR that needs your explicit attention.
When you have time please just have a look at this also.

2024-06-27 02:11 UTC, getchoo approved these changes
code looks good and this works as expected

i did notice something during testing though: when modpacks are installed, it seems no metadata is fetched along with it. this in turn causes this feature to be unavailable until the user does something to cause metadata fetching manually like checking for updates. this is obviously out of scope for this PR, but probably something to come back to in the future

2024-06-27 02:12 UTC, merged

2024-06-27 05:20 UTC, Trial97 commented
That is already tracked in this issue:https://github.com/PrismLauncher/PrismLauncher/issues/1730