Data pack management
PrismLauncher/PrismLauncher pull request #1905
Opened 2023-12-01 15:20 UTC by TheKodeToad

2024-06-15 21:10 UTC, Trial97 commented
I will remove this from 9.0 as no progress was made over 6 months. (let's add it to a milestone when this is ready)

2024-08-22 19:03 UTC, TheKodeToad commented
This is technically somewhat ready. But I should probably add global pack support.

2025-03-24 17:41 UTC, TheKodeToad commented
Gonna put this on 10.0 as I hope to finish it by then

2025-03-26 01:33 UTC, TheKodeToad commented
I think it's ready now. Unless I missed something.

2025-03-26 02:07 UTC, TheKodeToad commented
Found an issue. It seems it can end up updating to a version with the wrong loader.

2025-03-26 06:22 UTC, Trial97 commented on launcher/minecraft/mod/DataPackFolderModel.cpp
> +            }
Can you also make this an if statement?

2025-03-26 08:12 UTC, Trial97 commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
Can't we just detect in ModrinthAPI, where the search string is built that the resource type is datapack and replace the loader bit with a custom one without needing a fake loader?

2025-03-26 08:12 UTC, Trial97 commented on launcher/ui/pages/instance/ExternalResourcesPage.h
> +#include <QDialog>
?

2025-03-26 09:59 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
ResourceType is not in SearchArgs. I thought it would be a bit clunky to have a dataPacks boolean in SearchArgs too, and adding ResourceType wouldn't make sense either as it would only be used on Modrinth for data packs

2025-03-26 10:07 UTC, TheKodeToad commented
I forgot to implement CurseForge lol

2025-03-26 10:11 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
Also I don't think it is that illogical - Modrinth considers it a mod loader and it basically is - either implemented by vanilla for each world or by a global pack loader for all worlds.

2025-03-26 10:17 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
Wait got a bit confused - yes it is in SearchArgs but not in VersionSearchArgs. Since VersionSearchArgs contains an IndexedPack maybe the ResourceType could be put in there?

2025-03-26 10:25 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
The trouble is that would work for now, but it wouldn't work if we want to support downloading datapacks to the mods folder (for the case of "datapacks" which support mod loaders)

2025-03-26 10:25 UTC, Trial97 commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
Sure, we can put the resorceType in the IndexedPack or the VersionSearchArgs anything that would allow us not to propagate DataPack as a loader.

2025-03-26 10:27 UTC, Trial97 commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
Can you look into CF implementation also and see how it handles datapacks?
Maybe there will be a better way.

2025-03-26 14:05 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
>  Sure, we can put the resorceType in the IndexedPack or the VersionSearchArgs anything that would allow us not to propagate DataPack as a loader.

That would kind of conflict with allowing installing datapack jars to the mod folder. (Modrinth allows datapacks to contain versions repackages as jars for forge and fabric etc.)

2025-03-26 16:15 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
NVM i  think that makes the most sense in the long term if we actually want maintainable code :trollface:

2025-03-26 23:42 UTC, TheKodeToad commented on launcher/modplatform/ModIndex.h
> +    DataPack = 1 << 6
Turned out to be too hard
We also have other loader types for cauldron (which is literally for servers) so shrug

2025-04-15 15:12 UTC, Trial97 approved these changes

2025-04-28 21:25 UTC, Ryex requested changes

2025-04-28 21:25 UTC, Ryex commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    }
This needs to be updated to reflect the fix I recently pushed to prevent use after free in #3670

2025-04-29 08:14 UTC, TheKodeToad commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    }
I think I will go with
![image](https://github.com/user-attachments/assets/526fd987-4a20-4afb-8b06-9afe2059d430)

2025-04-29 08:16 UTC, Trial97 commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    }
do not start the ~~merge~~rebase yet wait a few minutes for https://github.com/PrismLauncher/PrismLauncher/pull/3677 it will be merged into dev once the action finish

2025-04-29 08:23 UTC, Trial97 commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    }
you can do the merge now :)

2025-04-29 11:19 UTC, TheKodeToad commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    }
I already did the merge before you posted that. but no conflicts luckily!

2025-04-29 11:21 UTC, Ryex commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
do datapacks *need* a mod loader>

2025-04-29 11:38 UTC, TheKodeToad commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
Trial made the same criticism. and I fiddled about and could not really find another good solution.

I said I would reopen if he came up with a better solution but that never happened – I think my solution ultimately ended up requiring many code changes and not even making that much sense.

2025-04-29 13:23 UTC, Ryex commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
I'm confused. the reason to use datapacks is often because they don't need a mod loader. what about our internal stuff requires a mod loader to allow management of data packs?

if such a requirement exists I would consider that a blocker for merging.

2025-04-29 13:25 UTC, Trial97 commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
a bit of context from previous discussions https://github.com/PrismLauncher/PrismLauncher/pull/1905#discussion_r2013580746
modrinth considers somehow datapacks as a loader or something

2025-04-29 16:49 UTC, TheKodeToad commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
> imo Adding a datapack should be no different than adding a resource pack ux wise

Indeed - it is the same in terms of UX
It is just in the loaders as modrinth considers it a loader and it makes it much easier to pass it through the code

2025-04-29 17:11 UTC, TheKodeToad commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
If you don't want to read my descent into insanity I can summarise it as this - though it has been a while since i thought about this:
- Modrinth has a datapack project type and a datapack loader.
- If you only want datapacks you need to filter the project search by both the datapack project type and data pack loader
- You also need to filter by the data pack loader on the versions - so the easiest option is to just add this to the ModLoader enum so it automatically applies to both.
- I tried more elaborate options like passing the project type into `VersionSearchArgs` too, or a boolean - but both of those values would only do something in very specific circumstances so it didn't feel worth it - and it also required changing a large amount of duplicated code to pass this data around

2025-05-31 17:23 UTC, TheKodeToad commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
@Ryex hello

2025-05-31 22:53 UTC, Ryex approved these changes
probably best to update the PR before merging but looks good otherwise

2025-05-31 22:54 UTC, Ryex commented on launcher/ui/pages/instance/DataPackPage.cpp
> +    auto profile = static_cast<MinecraftInstance*>(m_instance)->getPackProfile();
sorry, this answered my concerns

2025-06-01 18:26 UTC, Trial97 reviewed
close button on add datapack doesn't work

2025-06-01 19:24 UTC, TheKodeToad commented
The latest commit should fix that

2025-06-01 19:30 UTC, Trial97 approved these changes

2025-06-02 00:31 UTC, Mick235711 commented
I'm still a bit confused about this; I understand the need for passing DataPack as a ModLoader for easier filtering, but why does that prevent vanilla instances from having data packs? I think that is actually one of the only reasons people use datapacks, to avoid having a mod loader.

Is it possible (for example) to just set the mod loader to `DataPack` on vanilla instances instead of refusing to open the download dialog? Or, if that does not work, maybe just disable Modrinth downloading for vanilla instances...

(Also, the datapack button should probably be hidden/removed for world version less than 1.13)

2025-06-02 08:04 UTC, TheKodeToad commented
> I'm still a bit confused about this; I understand the need for passing DataPack as a ModLoader for easier filtering, but why does that prevent vanilla instances from having data packs? I think that is actually one of the only reasons people use datapacks, to avoid having a mod loader.

Oops - that's because I copy and pasted code from the mod page

2025-06-02 09:06 UTC, TheKodeToad commented
> (Also, the datapack button should probably be hidden/removed for version less than 1.13 -- though the version seems not being filtered on at all...)

The tab only shows when you enable it and the button on the worlds page is pretty unintrusive, so I don't think this is a blocker. (this would also be annoying to implement lol - I think with things like demo mode we *can* easily check whether a release is `>= <added version>` but it assumes it supports it for all snapshots)

Probably gonna merge this as Trial97 thinks it's alright and I have fixed the critical issue of it not working with vanilla (I guess like many of my PRs this is prone to conflict hell)

2025-06-02 09:18 UTC, merged