Fix bundled java detection on mac
PrismLauncher/PrismLauncher pull request #2333
Opened 2024-04-23 05:54 UTC by Trial97

fixes #2332

2024-04-23 08:44 UTC, timoreo22 approved these changes

2024-04-23 12:12 UTC, TheKodeToad commented on launcher/java/JavaUtils.cpp
> +    QString partialPath = QProcessEnvironment::systemEnvironment().value("LOCALAPPDATA", "");
Why are we using LOCALAPPDATA
That would make it AppData\Local\.minecraft when it is located in AppData\Roaming|.minecraft

2024-04-23 14:53 UTC, Trial97 commented on launcher/java/JavaUtils.cpp
> +    QString partialPath = QProcessEnvironment::systemEnvironment().value("LOCALAPPDATA", "");
You are right I should not need to check `AppData\Roaming\.minecraft\runtimes` folder(most likely doesn't exist)
But I use the AppData\Roaming prefix to locate where the Minecraft stores the java runtimes

2024-04-23 15:36 UTC, TheKodeToad commented on launcher/java/JavaUtils.cpp
> +    QString partialPath = QProcessEnvironment::systemEnvironment().value("LOCALAPPDATA", "");
huh? that does exist for the non ms store launcher
it's just it was detecting it from AppData\Local which never exists

2024-04-23 16:08 UTC, getchoo requested changes

2024-04-23 16:08 UTC, getchoo commented on launcher/java/JavaUtils.cpp
> +        FS::PathCombine(QFileInfo(localAppDataPath).absolutePath(), "Local", "Packages", "Microsoft.4297127D64EC6_8wekyb3d8bbwe");
```suggestion
        FS::PathCombine(QFileInfo(localAppDataPath).absolutePath(), "Packages", "Microsoft.4297127D64EC6_8wekyb3d8bbwe");
```

2024-04-23 16:11 UTC, getchoo approved these changes

2024-04-23 16:13 UTC, TheKodeToad approved these changes

2024-04-23 16:19 UTC, merged

2024-04-24 11:13 UTC, Testsr commented
It seems like this change has broken my Minecraft Launcher runtime detection.