Fix portable if manifest is missing
PrismLauncher/PrismLauncher pull request #2405
Opened 2024-05-16 14:23 UTC by Trial97

fixes #2191
Basically, we should not touch the `portable.txt` file on the update

2024-05-16 16:30 UTC, DioEgizio requested changes
That's not gonna fix that, look into the nsis code, we uninstall everything that was in the folder and reinstall again to not having residual DLLs that could cause issues. Honestly adding portable.txt to nsis installs shouldn't be a supported configuration, just use the portable .zip if you need that

2024-05-16 16:42 UTC, Trial97 commented
This is more like a fix for portable in case they delete the manifest file.
Here is the situation this solves:
- download and extract portable version
- delete the manifest file
- do a prism update
- now prism is no longer portable

Yeah I know that the situation described in the issue is not desired, but this doubles as both a fix for that situation but also for the mentioned one.  
So if this is not desired please close both the issue and PR.

2024-05-16 16:44 UTC, Trial97 commented on launcher/updater/prismupdater/PrismUpdater.cpp
> +        QMetaObject::invokeMethod(this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);
```suggestion
        QMetaObject::invokeMethod(
           this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);Qt::QueuedConnection);
```

2024-05-16 16:45 UTC, Trial97 commented on launcher/updater/prismupdater/PrismUpdater.cpp
> +           this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);Qt::QueuedConnection);
```suggestion
            this, [this, target_dir]() { moveAndFinishUpdate(target_dir); }, Qt::QueuedConnection);
```

2024-06-09 07:03 UTC, Ryex approved these changes
*le sigh* This is such a silly use case to support...

I suppose this is fine because portable is just a marker file and we won't be adding any data to it

2024-06-13 15:46 UTC, DioEgizio approved these changes

2024-06-13 16:16 UTC, merged