Add techinc client ID
PrismLauncher/PrismLauncher pull request #2806
Opened 2024-09-13 17:02 UTC by Trial97

fixes #2775

2024-09-13 18:02 UTC, getchoo requested changes
s/techinc/technic/g

2024-09-13 18:02 UTC, getchoo commented on launcher/Application.cpp
> +        m_settings->registerSetting("TechincClientID", "");
```suggestion
        // Custom Technic Client ID
        m_settings->registerSetting("TechnicClientID", "");
```

2024-09-13 18:02 UTC, getchoo commented on launcher/ui/pages/global/APIPage.cpp
> +    ui->techicClientID->setText(s->get("TechincClientID").toString());
```suggestion
    ui->techicClientID->setText(s->get("TechnicClientID").toString());
```

2024-09-13 18:02 UTC, getchoo commented on launcher/ui/pages/global/APIPage.cpp
> +    s->set("TechincClientID", ui->techicClientID->text());
```suggestion
    s->set("TechincClientID", ui->technicClientID->text());
```

2024-09-13 18:02 UTC, getchoo commented on launcher/ui/pages/global/APIPage.ui
> +          <string>Techinc Client ID</string>
```suggestion
          <string>Technic Client ID</string>
```

2024-09-13 18:02 UTC, getchoo commented on launcher/ui/pages/global/APIPage.ui
> +             <string>Enter a custom GUID client ID for Techinc here.</string>
```suggestion
             <string>Enter a custom GUID client ID for Technic here.</string>
```

2024-09-13 18:02 UTC, getchoo commented on launcher/ui/pages/modplatform/technic/TechnicModel.cpp
> +    auto clientId = APPLICATION->settings()->get("TechincClientID").toString();
```suggestion
    auto clientId = APPLICATION->settings()->get("TechnicClientID").toString();
```

2024-09-13 18:13 UTC, Trial97 commented on launcher/ui/pages/global/APIPage.ui
> +           <widget class="QLineEdit" name="techicClientID">
```suggestion
           <widget class="QLineEdit" name="technicClientID">
```

2024-09-13 19:42 UTC, TheKodeToad commented on launcher/ui/pages/global/APIPage.cpp
> +    s->set("TechincClientID", ui->technicClientID->text());
```suggestion
    s->set("TechnicClientID", ui->technicClientID->text());
```

2024-09-23 19:33 UTC, TheKodeToad approved these changes

2024-09-24 23:53 UTC, getchoo approved these changes

2024-09-24 23:55 UTC, merged