Add extra step to macos java install
PrismLauncher/PrismLauncher pull request #2820
Opened 2024-09-14 18:20 UTC by Trial97

Parent PR: #2069
fixes #2814

so basically the java downloads on mac add another layer to java
this ensures that there is a link to the bin directory on the root java folder

2024-09-14 20:38 UTC, Ryex approved these changes

2024-09-16 13:40 UTC, getchoo requested changes

2024-09-16 13:40 UTC, getchoo commented on launcher/java/download/SymlinkTask.cpp
> +    setStatus(tr("Check Java bin"));
```suggestion
    setStatus(tr("Checking for Java binary path"));
```

2024-09-16 13:40 UTC, getchoo commented on launcher/java/download/SymlinkTask.cpp
> +    setStatus(tr("Search for Java bin"));
```suggestion
    setStatus(tr("Searching for Java binary path"));
```

2024-09-16 13:40 UTC, getchoo commented on launcher/java/download/SymlinkTask.cpp
> +        emitFailed(tr("Failed to find bin java"));
```suggestion
        emitFailed(tr("Failed to find Java binary path"));
```

2024-09-16 13:40 UTC, getchoo commented on launcher/java/download/SymlinkTask.cpp
> +    setStatus(tr("Collect folders to symlink"));
```suggestion
    setStatus(tr("Collecting folders to symlink"));
```

2024-09-16 13:40 UTC, getchoo commented on launcher/java/download/SymlinkTask.cpp
> +    setStatus(tr("Symlink Java"));
```suggestion
    setStatus(tr("Symlinking Java binary path"));
```

2024-09-16 14:02 UTC, getchoo approved these changes
LGTM. It would be nice to have the OP of the issue test this before merging, though

2024-09-16 14:04 UTC, getchoo commented
This is also a follow up on the parent PR, so no need for a changelog entry imo

2024-09-16 16:30 UTC, Trial97 commented
> LGTM. It would be nice to have the OP of the issue test this before merging, though

We need to fix mac builds first but yeah I will ping OP about once they are merged

2024-09-17 05:44 UTC, merged