Updated formatting guidelines
PrismLauncher/PrismLauncher pull request #3067
Opened 2024-11-06 16:12 UTC by TheKodeToad

Aims to reflect how we are doing things now - or perhaps should be 😆 
Might be a little excessive

One thing I don't know about is whether we want to do PascalCase or SCREAMING_SNAKE_CASE enums. I just stuck with the latter as it is traditionally what is prefered.

2024-11-06 16:35 UTC, Trial97 approved these changes

2024-11-06 16:38 UTC, TayouVR approved these changes

2024-11-06 21:23 UTC, Ryex requested changes

2024-11-06 21:23 UTC, Ryex commented on CONTRIBUTING.md
> +- `const` global variables, `static const` class data members, macros, and enum constants should be formatted as `SCREAMING_SNAKE_CASE`: `LIGHT_GRAY`.
```suggestion
- `static const` class data members should be formatted as `camelCase` prefixed with `s_`: `s_staticDataMember`.
- `const` global variables, macros, and enum constants should be formatted as `SCREAMING_SNAKE_CASE`: `LIGHT_GRAY`.
```

2024-11-06 22:56 UTC, Ryex approved these changes

2024-11-06 23:34 UTC, getchoo approved these changes

2024-11-07 09:43 UTC, timoreo22 approved these changes

2024-11-07 11:43 UTC, merged

2024-11-08 07:03 UTC, Ryex commented
Btw, [these conventions could be enforced via clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html#readability-identifier-naming)
we already have the `.clang-tidy` file

2024-11-08 10:09 UTC, TheKodeToad commented
If we automatically change everything it will create a load of conflicts though

2024-11-08 10:42 UTC, Trial97 commented
I'm fine with rebasing all my PRs, we also did this with clang-format
Either in one go or each time we work on a PR we would have a commit dedicated to the rename.