Fix resource search
PrismLauncher/PrismLauncher pull request #3083
Opened 2024-11-08 22:12 UTC by Trial97

fixes: https://discord.com/channels/1031648380885147709/1303585964253249556/1304478773780942932
and it was introduced here: https://github.com/PrismLauncher/PrismLauncher/commit/803e26a4018d788178032b653fd06d1b8970b3a4#diff-99a0c396e944fade5391d69854c4b0c9cd9eecfe00b636c84c1159cab520a45bL92

2024-11-08 22:44 UTC, Ryex approved these changes

2024-11-09 11:45 UTC, TheKodeToad approved these changes
IDK how I ended up removing that

2024-11-09 11:46 UTC, TheKodeToad requested changes, later dismissed

2024-11-09 11:46 UTC, TheKodeToad commented on CONTRIBUTING.md
Wait NVM please drop this commit

2024-11-09 12:00 UTC, Trial97 commented on CONTRIBUTING.md
Why? Should I do that?

2024-11-09 12:26 UTC, Trial97 commented on CONTRIBUTING.md
Like I know it bleed from other PR but still I wanted to test the linting of markdown

2024-11-15 23:09 UTC, TheKodeToad approved these changes

2024-11-15 23:09 UTC, merged