Add naming check in `.clang-tidy` file
PrismLauncher/PrismLauncher pull request #3128
Opened 2024-11-23 17:27 UTC by QazCetelic

The [contributing docs](https://github.com/PrismLauncher/PrismLauncher/blob/develop/CONTRIBUTING.md#code-formatting) specify these naming guidelines:

> **We have no tool for enforcing names but please follow the following conventions for C++:**
> 
> - Class and type names should be formatted as `PascalCase`: `MyClass`.
> - Private or protected class data members should be formatted as `camelCase` prefixed with `m_`: `m_myCounter`.
> - Private or protected `static` class data members should be formatted as `camelCase` prefixed with `s_`: `s_instance`.
> - Public class data members should be formatted as `camelCase` without the prefix: `dateOfBirth`.
> - Public, private or protected `static const` class data members should be formatted as `SCREAMING_SNAKE_CASE`: `MAX_VALUE`.
> - Class function members should be formatted as `camelCase` without a prefix: `incrementCounter`.
> - Global functions and non-`const` global variables should be formatted as `camelCase` without a prefix: `globalData`.
> - `const` global variables, macros, and enum constants should be formatted as `SCREAMING_SNAKE_CASE`: `LIGHT_GRAY`.
> - Avoid inventing acronyms or abbreviations especially for a name of multiple words - like `tp` for `texturePack`.

This change to the `.clang-tidy` config makes those naming violations show up as warnings in the user's IDE.
![image](https://github.com/user-attachments/assets/05c4e9b1-19dc-4028-86d2-5c38f252db64)

2024-11-23 17:35 UTC, TheKodeToad requested changes
Thanks! Maybe remove "We have no tool for enforcing names" because that's no longer the case. Still, I think the descriptions of how things should be named should be kept. Maybe you could add "We have this configured for clang-tidy so some IDEs will show a warning".

2024-11-23 19:52 UTC, Trial97 approved these changes

2024-11-23 20:14 UTC, TheKodeToad approved these changes

2024-11-24 01:00 UTC, Ryex approved these changes

2024-11-24 12:12 UTC, timoreo22 approved these changes

2024-11-24 16:10 UTC, merged