add .zip artifacts for macOS
PrismLauncher/PrismLauncher pull request #337
Opened 2022-10-29 06:56 UTC by ryanccn

because yes

closes #221

2022-10-29 06:58 UTC, DioEgizio approved these changes

2022-10-29 06:59 UTC, DioEgizio commented on .github/workflows/build.yml
> +          path: PrismLauncher.zip
Wait... wouldn't this make a zip of a zip? Also you should update the release workflow

2022-10-29 13:57 UTC, flowln approved these changes

2022-10-29 14:17 UTC, Scrumplex requested changes
As I already wrote in the other thread:
.zip and .tar.gz work identically on macOS. I don't see a reason we would need both

2022-10-29 14:35 UTC, ryanccn commented
.zip is generally more commonly used for distribution of macOS apps, so it would be more familiar to users I guess

2022-10-29 14:40 UTC, TheKodeToad commented
> .zip is generally more commonly used for distribution of macOS apps, so it would be more familiar to users I guess

Afaik most mac users know what .tar.gz is, and double clicking on it (what most users would start with) extracts it anyway.

2022-11-02 03:08 UTC, ryanccn commented
Also, most software are distributed in multiple formats (at least for macOS apps this is very often the case) in case one format is unavailable or something. Generally nicer to have more artifacts/formats available IMO

2022-11-05 10:19 UTC, Scrumplex commented
So what's the game plan? I am up to distributing dmgs, but zips seem redundant to me if we already have tars.

2022-11-05 10:20 UTC, ryanccn commented
dmgs are quite slow and they're not incredibly useful

2022-11-27 17:45 UTC, closed without merging