add: Spooky Rory
PrismLauncher/PrismLauncher pull request #405
Opened 2022-11-05 23:01 UTC by AshtakaOOf

Idk how to do the spooky Halloween jumpscare lol

Signed-off-by: Adrien <66513643+AshtakaOOf@users.noreply.github.com>

2022-11-05 23:05 UTC, Scrumplex approved these changes

2022-11-05 23:26 UTC, santiagocezar requested changes

2022-11-05 23:26 UTC, santiagocezar commented on launcher/resources/backgrounds/backgrounds.qrc
> +        <file alias="rory-spooky">rory-spooky.png</file>
This should end with `-ween`

2022-11-05 23:26 UTC, santiagocezar commented on launcher/resources/backgrounds/backgrounds.qrc
> +        <file alias="rory-flat-spooky">rory-flat-spooky.png</file>
and yeah this too

2022-11-05 23:26 UTC, santiagocezar commented on launcher/ui/MainWindow.cpp
>              cat += "-ween";
or the suffix could be `-spooky` instead, which I think seems nicer

2022-11-05 23:47 UTC, Scrumplex commented on launcher/resources/backgrounds/backgrounds.qrc
> +        <file alias="rory-spooky">rory-spooky.png</file>
oops

2022-11-06 02:30 UTC, AshtakaOOf commented
AAAAAAh I pushed the wrong branch noooo

2022-11-06 06:10 UTC, DioEgizio approved these changes

2022-11-06 06:27 UTC, merged