Rename PolyMC to Prism
PrismLauncher/PrismLauncher pull request #54
Opened 2022-10-18 14:54 UTC by Samisafool

This was useful btw:
```
$ rg --regexp '[Pp]oly[Mm][Cc]+|[Pp]rims+' --ignore-case | grep -vE '//|\*|Prism|^COPYING.md'
$ find . -type f -exec sed -i 's|PolyMC - Minecraft Launcher|Prism Launcher - Minecraft Launcher|g' {} +
$ rg --regexp '[Pp]oly[Mm][Cc]+|[Pp]rims+' --ignore-case | grep -vE '^COPYING.md|PolyMC - Minecraft Launcher|Prism'
```

2022-10-18 15:04 UTC, TheKodeToad commented
I noticed it's also replaced in the LICENSE files. I wonder if this is OK or all contributors would need to give permission.

2022-10-18 15:06 UTC, DioEgizio commented on launcher/Application.cpp
> +        if (prismlauncherData.exists()) {
that's intended to be polymc

2022-10-18 15:07 UTC, DioEgizio commented
> I noticed it's also replaced in the LICENSE files. I wonder if this is OK or all contributors would need to give permission.

yeah better to keep polymc there for now

2022-10-18 15:08 UTC, MenacingPerson commented on launcher/Application.cpp
> +        if (prismlauncherData.exists()) {
Okay got it

2022-10-18 15:10 UTC, Samisafool commented on launcher/Application.cpp
> +        if (prismlauncherData.exists()) {
I think it's done

2022-10-18 15:11 UTC, Samisafool commented
> >  I noticed it's also replaced in the LICENSE files. I wonder if this is OK or all contributors would need to give permission.
> yeah better to keep polymc there for now

Technically, all PolyMC contributors are PrismLauncher contributors. I can revert easily though.

2022-10-18 17:48 UTC, Scrumplex requested changes

2022-10-18 17:48 UTC, Scrumplex commented on launcher/updater/GoUpdate.cpp
> +    // Next, check each file in PrismLauncher's folder and see if we need to update them.
```suggestion
    // Next, check each file in Prism Launcher's folder and see if we need to update them.
```

2022-10-18 17:48 UTC, Scrumplex commented on libraries/README.md
> +A PrismLauncher-specific library for probing system information.
```suggestion
A Prism Launcher-specific library for probing system information.
```

2022-10-18 17:48 UTC, Scrumplex commented on launcher/java/JavaUtils.cpp
> +    // javas stored in PrismLauncher's folder
```suggestion
    // javas stored in Prism Launcher's folder
```

2022-10-18 17:48 UTC, Scrumplex commented on launcher/minecraft/Library.h
> +    /// DEPRECATED: PrismLauncher-specific absolute URL. takes precedence over the implicit maven repo URL, if defined
```suggestion
    /// DEPRECATED: Prism Launcher-specific absolute URL. takes precedence over the implicit maven repo URL, if defined
```

2022-10-18 17:48 UTC, Scrumplex commented on launcher/minecraft/Library.h
> +     * PrismLauncher-specific type hint - modifies how the library is treated
```suggestion
     * Prism Launcher-specific type hint - modifies how the library is treated
```

2022-10-18 17:48 UTC, Scrumplex commented on launcher/minecraft/Library.h
> +     * storage - by default the local libraries folder in PrismLauncher, but could be elsewhere
```suggestion
     * storage - by default the local libraries folder in Prism Launcher, but could be elsewhere
```

2022-10-18 17:48 UTC, Scrumplex commented
Ideally, commit my suggestion in a batch

2022-10-19 08:39 UTC, DioEgizio reviewed
about renaming the images, you probably shouldn't do it since https://github.com/PrismLauncher/PrismLauncher/pull/92 already deals with that stuff

2022-10-19 08:57 UTC, DioEgizio commented
please [sign off your commits](https://github.com/PrismLauncher/PrismLauncher/pull/54/checks)

2022-10-19 08:59 UTC, Samisafool commented
I am quite new to this, sorry

2022-10-19 10:06 UTC, Scrumplex approved these changes
Thanks

2022-10-19 10:12 UTC, DioEgizio approved these changes
lgtm

2022-10-19 10:13 UTC, merged