Change discord invite to a banner
PrismLauncher/PrismLauncher pull request #75
Opened 2022-10-18 18:40 UTC by Gideon9212

To help direct people to support with a big banner.

2022-10-18 18:42 UTC, Gideon9212 commented
What it will look like.
![image](https://user-images.githubusercontent.com/24485150/196516786-5685fc4e-7d49-432b-ae03-66aa49fe9906.png)

2022-10-18 18:50 UTC, piprett requested changes
Small nitpick

2022-10-18 18:50 UTC, piprett commented on README.md
> +[![Support server invite](https://discordapp.com/api/guilds/1031648380885147709/widget.png?style=banner3)](https://discord.gg/hX4g537UNE)
I think "Support server invite" is not the best. The previous "Join the Discord Server" sounds better in my opinion.

2022-10-18 18:51 UTC, AshtakaOOf approved these changes
Pretty cool

2022-10-18 19:07 UTC, Gideon9212 commented on README.md
> +[![Support server invite](https://discordapp.com/api/guilds/1031648380885147709/widget.png?style=banner3)](https://discord.gg/hX4g537UNE)
I can change that if needed. It is a simple change.

2022-10-18 19:11 UTC, Gideon9212 commented
I updated that nitpick.
![image](https://user-images.githubusercontent.com/24485150/196522465-06678f17-ba57-4ae0-9e05-0ca48e507650.png)

2022-10-18 19:13 UTC, piprett approved these changes

2022-10-18 22:13 UTC, flowln approved these changes
thank you! just pleases resolve the conflict :p

2022-10-19 00:29 UTC, Gideon9212 commented
Conflict resolved.

2022-10-19 00:59 UTC, AshtakaOOf requested changes
Use the old invite in case the vanity dies because of boosters

2022-10-19 01:35 UTC, Gideon9212 commented
Swaped back to old invite.

2022-10-19 04:26 UTC, timoreo22 approved these changes

2022-10-19 04:27 UTC, merged