update README.md to provide more information
PrismLauncher/PrismLauncher pull request #87
Opened 2022-10-18 20:36 UTC by Joshument

2022-10-18 22:23 UTC, flowln approved these changes

2022-10-19 05:51 UTC, piprett requested changes

2022-10-19 05:51 UTC, piprett commented on README.md
> +- Join the [Discord Server](https://discord.gg/hX4g537UNE) for now.
#75 merge conflict

2022-10-20 19:09 UTC, txtsd commented
Thanks for your contribution.

2022-10-20 19:09 UTC, closed without merging