New Logo
PrismLauncher/PrismLauncher pull request #92
Opened 2022-10-18 21:57 UTC by Scrumplex

# TODO:
- [ ] need confirmation from one of the designers

2022-10-18 22:03 UTC, snessim commented
Currently has stitching problems. WIP

2022-10-18 22:05 UTC, AshtakaOOf commented
![icon-monochrome-dark](https://user-images.githubusercontent.com/66513643/196553756-bacc1e65-3657-4a9c-be3e-0d8e1dae5aac.svg)
![icon-monochrome-light](https://user-images.githubusercontent.com/66513643/196553770-050769ec-22cb-4d57-a0ae-acea698edc3d.svg)
Here are the minimal one for various purposes

2022-10-18 22:14 UTC, Sea-Kerman commented
Hmm, the minimal/monochrome ones don’t look very similar to the colored ones, perhaps add dividing gaps/differences in brightness to emulate the dirt block and spectrum

2022-10-18 22:33 UTC, TayouVR commented on launcher/ui/dialogs/AboutDialog.cpp
> +    stream << "<p>And everyone else who <a href='https://github.com/PolyMC/PolyMC/graphs/contributors'>contributed</a>!</p>\n";
```suggestion
    stream << "<p>And everyone else who <a href='https://github.com/PrismLauncher/PrismLauncher/graphs/contributors'>contributed</a>!</p>\n";
```
maybe update this already?

2022-10-18 23:17 UTC, AshtakaOOf requested changes
Replace the monochrome with the the tiny monochrome?

2022-10-19 00:09 UTC, NotNite commented
This line in the README: `Logo and branding also coming soon.` should be removed.

2022-10-19 07:27 UTC, Scrumplex commented
> Replace the monochrome with the the tiny monochrome?

Monochrome ones are not used right now. Just putting them into the repo, so we don't lose them. :D

2022-10-19 10:11 UTC, DioEgizio approved these changes

2022-10-19 11:03 UTC, timoreo22 approved these changes
Just so that this is ready to merge, i think we still have a few slight logo modifications

2022-10-19 11:06 UTC, DioEgizio commented
conflicting with develop

2022-10-19 11:41 UTC, merged

2022-10-23 04:16 UTC, jn64 commented
The logotype in the source svgs is already rendered to paths. Would be good to document the font used for future reference.

2022-10-23 04:42 UTC, snessim commented
The font is custom.