[WIP]Mod dependencies
PrismLauncher/PrismLauncher pull request #986
Opened 2023-04-09 17:44 UTC by Trial97

This will make sure to download mod dependencies automatically,
ToDo:
- [x] Get the dependencies from providers
- [ ] Add handle for required dependencies
- [ ] Add handle for incompatible dependencies

2023-04-09 20:25 UTC, Ryex commented
Just a heads up, you'll want to sign off your commits to make our DCO check happy and agree to our contributor agreement

`git commit -s`

or other sign off options in your git managment

2023-04-21 14:38 UTC, DioEgizio commented
`107.628 D | Task "GetModDependenciesTask(Get dependencies)" starting for the first time
   107.636 D | Task "SequentialTask(DependencyInfo: 306612)" starting for the first time
   107.638 D | Task "NetJob(306612::GetProject)" starting for the first time
   107.639 D | Task "Net::Download(0x60000249dd90)" starting for the first time
   107.639 D | Downloading  "https://api.curseforge.com/v1/mods/306612"
   107.783 D | Download succeeded: "https://api.curseforge.com/v1/mods/306612"
   107.784 D | Task "NetJob(306612::GetProject)" succeeded
   107.784 D | Task "NetJob(306612::Dependecy)" starting for the first time
   107.785 D | Task "Net::Download(0x60000249de40)" starting for the first time
   107.786 D | Downloading  "https://api.curseforge.com/v1/mods/306612/files?pageSize=10000&gameVersion=1.19.4&modLoaderType=%25"
   107.946 D | Download succeeded: "https://api.curseforge.com/v1/mods/306612/files?pageSize=10000&gameVersion=1.19.4&modLoaderType=%25"
   107.947 D | Task "NetJob(306612::Dependecy)" succeeded
   107.947 D | Task "SequentialTask(DependencyInfo: 306612)" succeeded
   107.950 D | Task "SequentialTask(DependencyInfo: P7dR8mSH)" starting for the first time
   107.951 D | Task "NetJob(P7dR8mSH::GetProject)" starting for the first time
   107.952 D | Task "Net::Download(0x60000249def0)" starting for the first time
   107.952 D | Downloading  "https://api.modrinth.com/v2/project/P7dR8mSH"
   108.200 D | Download succeeded: "https://api.modrinth.com/v2/project/P7dR8mSH"
   108.200 D | Task "NetJob(P7dR8mSH::GetProject)" succeeded
   108.201 D | Task "NetJob(P7dR8mSH::Dependecy)" starting for the first time
   108.202 D | Task "Net::Download(0x60000249dfa0)" starting for the first time
   108.202 D | Downloading  "https://api.modrinth.com/v2/version/unERf4ZJ"
   108.362 D | Download succeeded: "https://api.modrinth.com/v2/version/unERf4ZJ"
   108.362 D | Task "NetJob(P7dR8mSH::Dependecy)" succeeded
   108.362 D | Task "SequentialTask(DependencyInfo: P7dR8mSH)" succeeded
   108.363 D | Task "GetModDependenciesTask(Get dependencies)" succeeded
   108.368 F | ASSERT: "it != pack.versions.end()" in file /Users/runner/work/PrismLauncher/PrismLauncher/launcher/ui/dialogs/ResourceDownloadDialog.cpp, line 200`


got it to crash just installing random mods from cf and from modrinth

also you should fix the spelling, it's "Dependency", not "Dependecy"

2023-04-21 16:17 UTC, Trial97 commented
I can reproduce the crash mentioned on the develop branch by selecting the same mod from modrinth and curseforge. Once I choose the mod in the second provider the crash happens.
Should I open an issue or just fix it here.

2023-04-21 16:22 UTC, Ryex commented
> I can reproduce the crash mentioned on the develop branch by selecting the same mod from modrinth and curseforge. Once I choose the mod in the second provider the crash happens. Should I open an issue or just fix it here.

both?
It would be nice to track the cause with an issue. but not much sense making a separate PR since this issue is going to be important for the usability of this PR.

2023-04-21 16:28 UTC, DioEgizio commented
I mean since it happens on develop, it might make sense to fix it on a separate pr

2023-04-21 18:09 UTC, Trial97 commented
Opened the issue: https://github.com/PrismLauncher/PrismLauncher/issues/1028 
and the PR that solves it:https://github.com/PrismLauncher/PrismLauncher/pull/1029

2023-05-02 23:40 UTC, Ryex commented
could we consider moving this to  to 7.0 since it's already read for review? the users moving form curse forge will feel it's absence.

2023-05-03 02:08 UTC, Ryex requested changes
This is very well put together, thanks.

I spotted a spelling typo on `PackDependecny`, should be able to fix them all with a refactor command to change the name. to `PackDependency`

It would be nice to mark the added mods as required by another mod. I left comments as to how that could be achieved. Not *required* for this I guess but I think it would be a nice bit of polish.

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> + *  Copyright (c) 2022 flowln <flowlnlnln@gmail.com>
Copyright should read "PrismLauncher"

and really every file you touch should have it's copyright notice updated.

Also, instead of adding Flow's contact info for the new files she didn't write feel free to add your own (if your comfortable with that, I added my name but use my private github email)

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> + *  Copyright (C) 2022 Sefa Eyeoglu <contact@scrumplex.net>
same copyright issue :P

2023-05-03 02:08 UTC, Ryex commented on launcher/ui/dialogs/ReviewMessageBox.h
> +        QString provider;
it would be nice to extend `ResourceInformation` with a `required_by` field  that could be an Optional for the name of the mode that required this mod first.

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +        ModPlatform::Dependency dependency;
```suggestion
    struct PackDependency {
        ModPlatform::Dependency dependency;
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +        PackDependecny(const ModPlatform::IndexedPack& p, const ModPlatform::IndexedVersion& v)
```suggestion
        PackDependency(){};
        PackDependency(const ModPlatform::IndexedPack& p, const ModPlatform::IndexedVersion& v)
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +                                    QList<std::shared_ptr<PackDependecny>> selected);
```suggestion
                                    QList<std::shared_ptr<PackDependency>> selected);
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +    auto getDependecies() const -> QList<std::shared_ptr<PackDependecny>> { return m_pack_dependencies; }
```suggestion
    auto getDependecies() const -> QList<std::shared_ptr<PackDependency>> { return m_pack_dependencies; }
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +    QList<std::shared_ptr<PackDependecny>> m_selected;
```suggestion
    QList<std::shared_ptr<PackDependency>> m_pack_dependencies;
    QList<std::shared_ptr<Metadata::ModStruct>> m_mods;
    QList<std::shared_ptr<PackDependency>> m_selected;
```

2023-05-03 02:08 UTC, Ryex commented on launcher/ui/dialogs/ResourceDownloadDialog.cpp
> +        QList<std::shared_ptr<GetModDependenciesTask::PackDependecny>> selectedVers;
```suggestion
        QList<std::shared_ptr<GetModDependenciesTask::PackDependency>> selectedVers;
```

2023-05-03 02:08 UTC, Ryex commented on launcher/ui/dialogs/ResourceDownloadDialog.cpp
> +            selectedVers.append(std::make_shared<GetModDependenciesTask::PackDependecny>(selected->getPack(), selected->getVersion()));
```suggestion
            selectedVers.append(std::make_shared<GetModDependenciesTask::PackDependency>(selected->getPack(), selected->getVersion()));
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +                                               QList<std::shared_ptr<PackDependecny>> selected)
```suggestion
                                               QList<std::shared_ptr<PackDependency>> selected)
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +                                            [&ver_dep, providerName](std::shared_ptr<PackDependecny> i) {
```suggestion
                                            [&ver_dep, providerName](std::shared_ptr<PackDependency> i) {
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +    auto pDep = std::make_shared<PackDependecny>();
```suggestion
    auto pDep = std::make_shared<PackDependency>();
```

2023-05-03 02:08 UTC, Ryex commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +    };
along with modifying `ResourceInformation` add a `required_by` field to `PackDependency` here too.

2023-05-03 02:08 UTC, Ryex commented on launcher/ui/dialogs/ResourceDownloadDialog.cpp
> +            }
with the `required_by` filed added to `PackDependency` a map or pair list of `ModPack::IndexedVerison` 's to track what required what could be built here.

2023-05-03 02:08 UTC, Ryex commented on launcher/ui/dialogs/ResourceDownloadDialog.cpp
> +            { task, selected->getFilename(), selected->getCustomPath(), ProviderCaps.name(selected->getProvider()) });
the `ResourceInformation::requiredBy` field  could then be set here  from the recorded information.

2023-05-03 02:08 UTC, Ryex commented on launcher/ui/dialogs/ReviewMessageBox.cpp
> +
if adding the `required_by` field then add it's display here.
```suggestion
    
    auto requiredByItem = new QTreeWidgetItem(itemTop);
    requiredByItem->setText(0, tr("Required by: %1").arg(info.required_by));
```

If the `required_by` field uses an `std::option` then of course the check should be made.

2023-05-04 19:36 UTC, Trial97 commented
All the comments should be addressed.
But remember this depends on https://github.com/PrismLauncher/PrismLauncher/pull/1029 so that PR should be accepted first(this is why I always merge it in this branch).

2023-06-02 22:21 UTC, Trial97 commented
A little late (I just found out this issue), but this PR should close #116
It doesn't implement the design from there(with filters and stuff:https://github.com/PrismLauncher/PrismLauncher/issues/116#issuecomment-1382818873) but it achieves the same goal.

2023-06-18 13:29 UTC, TheKodeToad requested changes
here are some suggestions!

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +    auto c_dependencies = QList<ModPlatform::Dependency>();
```suggestion
    QList<ModPlatform::Dependency> c_dependencies;
```

I don't understand why you'd use auto if it makes the code more verbose

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +        }
woah! :laughing: 

can you make this use `continue`? it looks like it should be possible. currently it appears to be shadowing `dep`... I have no idea why that's possible!

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +static Version mcVersions(BaseInstance* inst)
maybe `mcVersion` is a better name? there will only be one

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +            qWarning() << *responseInfo;
Maybe the latter should be using `qDebug`?

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.h
> +        PackDependency(){};
```suggestion
        PackDependency() {}
```

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/modplatform/ResourceAPI.h
> +        }
Why do you need this? Isn't this the default behaviour?

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/modplatform/flame/FlameModIndex.cpp
> +    QVector<ModPlatform::IndexedVersion> unsortedVersions;
it seems weird to call something which will be sorted `unsorted`

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/modplatform/flame/FlameModIndex.cpp
> +        }
Since there is no handling for `default`, `type` would be uninitialised. I suggest using an additional `UNKNOWN` value.

this would cause some very weird bugs if CurseForge were to add another dependency type! :ioa:

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/modplatform/modrinth/ModrinthPackIndex.cpp
> +            dependency.type = ModPlatform::DependencyType::EMBEDDED;
Same as in FlameModIndex

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/modplatform/modrinth/ModrinthPackIndex.cpp
> +    QVector<ModPlatform::IndexedVersion> unsortedVersions;
Same as in FlameModIndex

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/ui/dialogs/ResourceDownloadDialog.cpp
> +QStringList getReqiredBy(QList<ResourceDownloadDialog::DownloadTaskPtr> tasks, QVariant addonId)
`Required` (not important)

2023-06-18 13:29 UTC, TheKodeToad commented on launcher/ui/dialogs/ResourceDownloadDialog.cpp
> +            }
```suggestion
        } else {
            for (auto dep : task->getDependecies())
                addResource(dep->pack, dep->version);
        }
```

less confusing imo

or
```suggestion
        } else
            for (auto dep : task->getDependecies())
                addResource(dep->pack, dep->version);
```

but it feels weird with else tbh

2023-06-18 21:31 UTC, Trial97 commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +            qWarning() << *responseInfo;
I want to keep qWarning as it is not an error that can only happen on debug.
Also, qWarning is used every time the mod info is requested.

2023-06-19 02:08 UTC, Ryex approved these changes
LGTM

2023-06-19 10:32 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +            qWarning() << *responseInfo;
Seems it's more typical in the codebase to do `qDebug()` for the raw data

2023-06-19 10:42 UTC, Trial97 commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +            qWarning() << *responseInfo;
So only the `responseInfo` should be in `qDebug`? Can we keep the error message as a warning?

2023-06-19 11:06 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +            qWarning() << *responseInfo;
you don't have to do this!
but yes, I wasn't suggesting changing the error message

2023-06-19 11:15 UTC, DioEgizio commented
something broke in the mod version validation

7.1:
<img width="1123" alt="7.1" src="https://github.com/PrismLauncher/PrismLauncher/assets/83089242/c69480dd-5624-4315-991e-09f92639aedf">

this pr:
<img width="1123" alt="this pr" src="https://github.com/PrismLauncher/PrismLauncher/assets/83089242/2c268d51-a49b-4b8d-af85-9ccdfa37cf31">

2023-06-19 11:19 UTC, TheKodeToad commented
Modrinth lets the author either depend on a project or a version. This doesn't work with version dependencies like I used here (tbh I should probably change this) as it assumes `project_id` to be part of the JSON object!

![image](https://github.com/PrismLauncher/PrismLauncher/assets/57493648/3d94b903-aaea-4162-8abe-6c29b1e5df74)

2023-06-19 11:20 UTC, TheKodeToad commented
Wait lol. I didn't see Dio's comment.

2023-06-19 11:20 UTC, DioEgizio commented
<img width="612" alt="image" src="https://github.com/PrismLauncher/PrismLauncher/assets/83089242/a4723f67-a004-444c-ae3b-cd05c6552f10">
this tries to download Fabric API even on Quilt and with qfapi in the download list. Perhaps we should have a system to use qfapi anyways on quilt and to not try to download it automatically download it as a dep

2023-06-19 11:38 UTC, TheKodeToad commented
Hmm, QFAPI has Fabric API marked as an embedded library. Maybe you could take advantage of that!

2023-06-19 11:49 UTC, DioEgizio commented
> Hmm, QFAPI has Fabric API marked as an embedded library. Maybe you could take advantage of that!
> 
> Then again, that may not work well for every case

Remember that CF exists. Also that way it would still download fapi if you don't manually install qfapi

2023-06-19 12:05 UTC, TheKodeToad commented
![image](https://github.com/PrismLauncher/PrismLauncher/assets/57493648/361bee0b-1485-4248-9746-881a2eea6250)
cf has something like this too...
but in a *lot* of cases skipping embedded mods would simply cause issues

2023-06-19 14:43 UTC, Trial97 commented
Fixed the version selection without project_id and I will start looking into the quilt vs fabric stuff.

2023-06-19 18:22 UTC, Trial97 commented
Also added an override for Quilt/Fabric 2 mods(API and Kotlin) that conflict.

2023-06-20 09:56 UTC, DioEgizio commented
seems to fail at automatically installing qkl on mods that need flk

also this needs to be done for qfapi only on mc >= 1.18.2 and for qkl only on mc >= 1.19.2, else prism doesn't know what to download on those versions and gets stuck

![image](https://github.com/PrismLauncher/PrismLauncher/assets/83089242/61d15bd0-ed76-424e-8c7d-63eba71f72d9)

2023-06-20 10:30 UTC, Trial97 commented
I choose to go with: if you are on quilt and the project is qfapi but no version for it, download the fabric equivalent(this is only for getDependecy task)

2023-06-20 16:41 UTC, DioEgizio commented
not really related to this pr but this way if downloaded from cf it also downloads the apis on cf for quilt, but this way you can't update them because still only searches for fabric there. We really need to add quilt support to cf mod downloading/updating. But otherwise this works fine now!

2023-06-20 16:42 UTC, DioEgizio approved these changes

2023-06-24 12:47 UTC, TheKodeToad requested changes
thank you! just one thing you forgot to translate :p

2023-06-24 12:47 UTC, TheKodeToad commented on launcher/minecraft/mod/tasks/GetModDependenciesTask.cpp
> +    : SequentialTask(parent, "Get dependencies")
```suggestion
    : SequentialTask(parent, tr("Get dependencies"))
```

2023-06-24 12:47 UTC, TheKodeToad commented on launcher/modplatform/flame/FlameModIndex.cpp
> +                default:
```suggestion
            default:
```

2023-06-24 13:01 UTC, Trial97 commented
With this I tink this PR is eligible to be merged

2023-06-24 13:03 UTC, TheKodeToad approved these changes
A very nice feature!

2023-06-24 13:04 UTC, merged